import type { Project, User, ActivityItem, Stage, Task, JournalEntry } from './types'

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alex Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    skills: ['React', 'TypeScript', 'Node.js'],
    completedTasks: 24,
    activityLevel: 'high',
  },
  {
    id: '2',
    name: 'Maria Santos',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria',
    skills: ['Python', 'Django', 'PostgreSQL'],
    completedTasks: 18,
    activityLevel: 'medium',
  },
  {
    id: '3',
    name: 'James Miller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=james',
    skills: ['UI/UX', 'Figma', 'CSS'],
    completedTasks: 12,
    activityLevel: 'high',
  },
  {
    id: '4',
    name: 'Elena Kowalski',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena',
    skills: ['DevOps', 'AWS', 'Docker'],
    completedTasks: 31,
    activityLevel: 'high',
  },
  {
    id: '5',
    name: 'David Park',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    skills: ['Go', 'Kubernetes', 'gRPC'],
    completedTasks: 8,
    activityLevel: 'low',
  },
]

const createStages = (projectId: string): Stage[] => [
  {
    id: `${projectId}-s1`,
    title: 'Foundation',
    goal: 'Set up the project infrastructure and core architecture',
    tasks: [
      {
        id: `${projectId}-t1`,
        title: 'Initialize repository and CI/CD',
        estimateMinutes: 45,
        assignedUser: mockUsers[0],
        commitment: 'Completed on Apr 15',
        deadline: new Date(Date.now() + 86400000 * 2),
        completed: true,
        stageId: `${projectId}-s1`,
      },
      {
        id: `${projectId}-t2`,
        title: 'Set up database schema',
        estimateMinutes: 60,
        assignedUser: mockUsers[1],
        commitment: 'Completed on Apr 16',
        deadline: new Date(Date.now() + 86400000 * 3),
        completed: true,
        stageId: `${projectId}-s1`,
      },
      {
        id: `${projectId}-t3`,
        title: 'Configure authentication flow',
        estimateMinutes: 90,
        assignedUser: mockUsers[3],
        commitment: 'I will finish this by Apr 22',
        deadline: new Date(Date.now() + 86400000 * 4),
        completed: false,
        stageId: `${projectId}-s1`,
      },
    ],
    deadline: new Date(Date.now() + 86400000 * 5),
    completed: false,
    order: 1,
  },
  {
    id: `${projectId}-s2`,
    title: 'Core Features',
    goal: 'Implement the main user-facing functionality',
    tasks: [
      {
        id: `${projectId}-t4`,
        title: 'Build user dashboard component',
        estimateMinutes: 120,
        deadline: new Date(Date.now() + 86400000 * 8),
        completed: false,
        stageId: `${projectId}-s2`,
      },
      {
        id: `${projectId}-t5`,
        title: 'Create API endpoints for data',
        estimateMinutes: 90,
        deadline: new Date(Date.now() + 86400000 * 9),
        completed: false,
        stageId: `${projectId}-s2`,
      },
      {
        id: `${projectId}-t6`,
        title: 'Implement search functionality',
        estimateMinutes: 75,
        deadline: new Date(Date.now() + 86400000 * 10),
        completed: false,
        stageId: `${projectId}-s2`,
      },
    ],
    deadline: new Date(Date.now() + 86400000 * 12),
    completed: false,
    order: 2,
  },
  {
    id: `${projectId}-s3`,
    title: 'Polish & Deploy',
    goal: 'Refine the UI and prepare for production deployment',
    tasks: [
      {
        id: `${projectId}-t7`,
        title: 'Add loading states and error handling',
        estimateMinutes: 60,
        deadline: new Date(Date.now() + 86400000 * 15),
        completed: false,
        stageId: `${projectId}-s3`,
      },
      {
        id: `${projectId}-t8`,
        title: 'Write deployment documentation',
        estimateMinutes: 45,
        deadline: new Date(Date.now() + 86400000 * 16),
        completed: false,
        stageId: `${projectId}-s3`,
      },
    ],
    deadline: new Date(Date.now() + 86400000 * 18),
    completed: false,
    order: 3,
  },
]

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'DevFlow Analytics',
    description: 'Real-time analytics dashboard for development teams to track productivity and code quality metrics.',
    status: 'active',
    health: 'healthy',
    participants: [mockUsers[0], mockUsers[1], mockUsers[2]],
    stages: createStages('1'),
    progress: 65,
    techStack: ['React', 'TypeScript', 'PostgreSQL', 'GraphQL'],
    roles: ['Frontend Developer', 'Backend Developer', 'Designer'],
    rolesNeeded: [],
    overdueTasks: 0,
    currentStage: 2,
    totalStages: 3,
    completedTasks: 5,
    totalTasks: 8,
    nextAction: { title: 'Build user dashboard component', estimateMinutes: 120 },
    createdAt: new Date(Date.now() - 86400000 * 14),
    updatedAt: new Date(),
  },
  {
    id: '2',
    title: 'CloudSync Storage',
    description: 'Distributed file storage system with end-to-end encryption and real-time collaboration features.',
    status: 'slow',
    health: 'slowing',
    participants: [mockUsers[1], mockUsers[3]],
    stages: createStages('2'),
    progress: 35,
    techStack: ['Go', 'AWS', 'Redis', 'Docker'],
    roles: ['Backend Developer', 'DevOps Engineer'],
    rolesNeeded: ['Frontend Developer'],
    overdueTasks: 2,
    currentStage: 1,
    totalStages: 3,
    completedTasks: 2,
    totalTasks: 8,
    nextAction: { title: 'Fix file upload timeout bug', estimateMinutes: 45 },
    createdAt: new Date(Date.now() - 86400000 * 21),
    updatedAt: new Date(Date.now() - 86400000 * 5),
  },
  {
    id: '3',
    title: 'AI Code Review',
    description: 'Automated code review tool powered by machine learning for detecting bugs and suggesting improvements.',
    status: 'stalled',
    health: 'at_risk',
    participants: [mockUsers[0], mockUsers[4]],
    stages: createStages('3'),
    progress: 20,
    techStack: ['Python', 'TensorFlow', 'FastAPI'],
    roles: ['ML Engineer', 'Backend Developer'],
    rolesNeeded: ['ML Engineer', 'Backend Developer'],
    overdueTasks: 4,
    currentStage: 1,
    totalStages: 3,
    completedTasks: 1,
    totalTasks: 8,
    nextAction: { title: 'Complete API endpoint for reviews', estimateMinutes: 60 },
    createdAt: new Date(Date.now() - 86400000 * 30),
    updatedAt: new Date(Date.now() - 86400000 * 12),
  },
  {
    id: '4',
    title: 'TeamPulse Chat',
    description: 'Modern team communication platform with threaded conversations and smart notifications.',
    status: 'revival',
    health: 'slowing',
    participants: [mockUsers[2], mockUsers[3], mockUsers[4]],
    stages: createStages('4'),
    progress: 48,
    techStack: ['Next.js', 'WebSocket', 'MongoDB'],
    roles: ['Full Stack Developer', 'Designer'],
    rolesNeeded: ['Full Stack Developer'],
    overdueTasks: 1,
    currentStage: 2,
    totalStages: 3,
    completedTasks: 4,
    totalTasks: 8,
    nextAction: { title: 'Implement thread notifications', estimateMinutes: 90 },
    createdAt: new Date(Date.now() - 86400000 * 45),
    updatedAt: new Date(Date.now() - 86400000 * 1),
  },
  {
    id: '5',
    title: 'OpenAPI Generator',
    description: 'Tool for generating type-safe API clients from OpenAPI specifications.',
    status: 'completed',
    health: 'healthy',
    participants: [mockUsers[0], mockUsers[1], mockUsers[3], mockUsers[4]],
    stages: createStages('5'),
    progress: 100,
    techStack: ['TypeScript', 'Node.js', 'CLI'],
    roles: ['Backend Developer'],
    rolesNeeded: [],
    overdueTasks: 0,
    currentStage: 3,
    totalStages: 3,
    completedTasks: 8,
    totalTasks: 8,
    createdAt: new Date(Date.now() - 86400000 * 60),
    updatedAt: new Date(Date.now() - 86400000 * 3),
  },
  {
    id: '6',
    title: 'Mesh API Gateway',
    description: 'Service mesh implementation with intelligent routing and automatic load balancing.',
    status: 'active',
    health: 'healthy',
    participants: [mockUsers[3], mockUsers[4]],
    stages: createStages('6'),
    progress: 42,
    techStack: ['Rust', 'gRPC', 'Kubernetes'],
    roles: ['Systems Engineer', 'DevOps Engineer'],
    rolesNeeded: [],
    overdueTasks: 0,
    currentStage: 2,
    totalStages: 3,
    completedTasks: 3,
    totalTasks: 8,
    nextAction: { title: 'Add rate limiting middleware', estimateMinutes: 75 },
    createdAt: new Date(Date.now() - 86400000 * 10),
    updatedAt: new Date(Date.now() - 86400000 * 0.5),
  },
  {
    id: '7',
    title: 'DataViz Studio',
    description: 'Interactive data visualization tool with drag-and-drop chart builder and export capabilities.',
    status: 'slow',
    health: 'at_risk',
    participants: [mockUsers[2]],
    stages: createStages('7'),
    progress: 15,
    techStack: ['D3.js', 'React', 'Canvas'],
    roles: ['Frontend Developer', 'Designer'],
    rolesNeeded: ['Frontend Developer', 'Backend Developer'],
    overdueTasks: 3,
    currentStage: 1,
    totalStages: 3,
    completedTasks: 1,
    totalTasks: 8,
    nextAction: { title: 'Create bar chart component', estimateMinutes: 30 },
    createdAt: new Date(Date.now() - 86400000 * 18),
    updatedAt: new Date(Date.now() - 86400000 * 8),
  },
]

export const mockActivities: ActivityItem[] = [
  {
    id: '1',
    type: 'task_completed',
    user: mockUsers[0],
    description: 'Completed "Initialize repository and CI/CD"',
    timestamp: new Date(Date.now() - 3600000 * 2),
    projectId: '1',
  },
  {
    id: '2',
    type: 'user_joined',
    user: mockUsers[2],
    description: 'Joined the project as Designer',
    timestamp: new Date(Date.now() - 3600000 * 5),
    projectId: '1',
  },
  {
    id: '3',
    type: 'stage_completed',
    user: mockUsers[1],
    description: 'Completed stage "Foundation"',
    timestamp: new Date(Date.now() - 86400000 * 1),
    projectId: '1',
  },
  {
    id: '4',
    type: 'task_completed',
    user: mockUsers[1],
    description: 'Completed "Set up database schema"',
    timestamp: new Date(Date.now() - 86400000 * 1.5),
    projectId: '1',
  },
  {
    id: '5',
    type: 'user_update',
    user: mockUsers[3],
    description: 'Updated task estimate for "Configure authentication flow"',
    timestamp: new Date(Date.now() - 86400000 * 2),
    projectId: '1',
  },
  {
    id: '6',
    type: 'project_update',
    user: mockUsers[0],
    description: 'Updated project description',
    timestamp: new Date(Date.now() - 86400000 * 3),
    projectId: '1',
  },
]

export const mockJournalEntries: JournalEntry[] = [
  {
    id: 'j1',
    whatWasDone: 'Set up database schema',
    user: mockUsers[1],
    result: 'API ready for CRUD operations',
    nextStep: 'Implement authentication flow',
    timestamp: new Date(Date.now() - 86400000 * 1.5),
    projectId: '1',
  },
  {
    id: 'j2',
    whatWasDone: 'Initialize repository and CI/CD',
    user: mockUsers[0],
    result: 'GitHub Actions pipeline working',
    nextStep: 'Set up database schema',
    timestamp: new Date(Date.now() - 86400000 * 3),
    projectId: '1',
  },
  {
    id: 'j3',
    whatWasDone: 'Created project structure',
    user: mockUsers[0],
    result: 'Next.js app with TypeScript configured',
    nextStep: 'Initialize repository and CI/CD',
    timestamp: new Date(Date.now() - 86400000 * 5),
    projectId: '1',
  },
]

export const getProjectById = (id: string): Project | undefined => {
  return mockProjects.find(p => p.id === id)
}

export const getActivitiesByProjectId = (projectId: string): ActivityItem[] => {
  return mockActivities.filter(a => a.projectId === projectId)
}

export const getJournalEntriesByProjectId = (projectId: string): JournalEntry[] => {
  return mockJournalEntries.filter(e => e.projectId === projectId)
}
